// Package frpmaster frpc 多节点 Master 控制面。
//
// 把 NetPanel 从「单机 frp 管理」扩展到「多节点 frpc 集中管控」：Master（面板）
// 统一注册/管理任意数量的远程 frpc 节点，生成并下发 frpc.toml；节点通过控制
// 通道回传心跳与隧道状态。
// 规划：#50（frpc 多节点 Master 模式）、#84（多线路池总方案 M3）。
package frpmaster

import (
	"strconv"
	"strings"
)

// Proxy 一条 frpc 代理（frpc.toml 中 [[proxies]] 的建模，M3 子集）。
type Proxy struct {
	Name           string
	Type           string // tcp/udp/http/https/stcp/sudp/xtcp
	LocalIP        string
	LocalPort      int
	RemotePort     int    // tcp/udp 远程端口
	CustomDomains  string // http/https，逗号分隔
	Subdomain      string // http/https
	SecretKey      string // stcp/sudp/xtcp 私密访问
	UseEncryption  bool
	UseCompression bool
}

// ClientConfig 一个 frpc 节点的完整配置（frpc.toml 内容建模）。
// 使用 frp 0.52+ 的 camelCase 键格式。
type ClientConfig struct {
	ServerAddr        string
	ServerPort        int
	Token             string
	User              string
	Transport         string // tcp/kcp/quic/websocket/wss，空 = 默认 tcp
	TLSEnable         bool
	LoginFailExit     bool
	LogLevel          string // trace/debug/info/warn/error，空 = 默认 info
	DialServerTimeout int
	HeartbeatInterval int
	Proxies           []Proxy
}

// tomlStr 输出带双引号与转义的字符串字面量。
func tomlStr(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`, "\n", `\n`)
	return `"` + r.Replace(s) + `"`
}

// GenerateFrpcToml 生成 frpc.toml 内容。
//
// M3 生成 [common]（连接 frps 所需的最小集）与已配置的 [[proxies]] 子集；
// 未设置的字段不输出，frp 侧走默认值。仅输出 tcp/udp/http/https/stcp/xtcp
// 常用代理类型，字段缺失时跳过对应代理并附注释说明。
func GenerateFrpcToml(cfg ClientConfig) string {
	var b strings.Builder
	b.WriteString("# frpc.toml generated by NetPanel frpmaster\n")

	if cfg.ServerAddr != "" {
		b.WriteString("serverAddr = " + tomlStr(cfg.ServerAddr) + "\n")
	}
	port := cfg.ServerPort
	if port <= 0 {
		port = 7000
	}
	b.WriteString("serverPort = " + strconv.Itoa(port) + "\n")
	if cfg.User != "" {
		b.WriteString("user = " + tomlStr(cfg.User) + "\n")
	}
	if cfg.Token != "" {
		b.WriteString("[auth]\ntoken = " + tomlStr(cfg.Token) + "\n")
	}
	if cfg.Transport != "" && cfg.Transport != "tcp" {
		b.WriteString("[transport]\nprotocol = " + tomlStr(cfg.Transport) + "\n")
	}
	b.WriteString("[tls]\nenable = " + strconv.FormatBool(cfg.TLSEnable) + "\n")
	b.WriteString("[log]\nlevel = " + tomlStr(defaultStr(cfg.LogLevel, "info")) + "\n")
	if cfg.LoginFailExit {
		b.WriteString("loginFailExit = true\n")
	}

	for _, p := range cfg.Proxies {
		b.WriteString(proxyToml(p))
	}
	return b.String()
}

// proxyToml 渲染一条 [[proxies]]；字段不满足类型要求时输出注释说明并跳过。
func proxyToml(p Proxy) string {
	if p.Name == "" {
		return "# [skip] proxy 缺少 name\n"
	}
	typ := strings.ToLower(p.Type)
	if typ == "" {
		typ = "tcp"
	}
	// 类型要求：tcp/udp 需 remotePort；stcp/sudp/xtcp 需 secretKey；
	// http/https 需 customDomains 或 subdomain。
	switch typ {
	case "tcp", "udp":
		if p.RemotePort <= 0 {
			return "# [skip] proxy " + p.Name + " (" + typ + ") 缺少 remotePort\n"
		}
	case "http", "https":
		if p.CustomDomains == "" && p.Subdomain == "" {
			return "# [skip] proxy " + p.Name + " (" + typ + ") 缺少 customDomains/subdomain\n"
		}
	case "stcp", "sudp", "xtcp":
		if p.SecretKey == "" {
			return "# [skip] proxy " + p.Name + " (" + typ + ") 缺少 secretKey\n"
		}
	default:
		return "# [skip] proxy " + p.Name + " 不支持的 type: " + typ + "\n"
	}

	var b strings.Builder
	b.WriteString("\n[[proxies]]\n")
	b.WriteString("name = " + tomlStr(p.Name) + "\n")
	b.WriteString("type = " + tomlStr(typ) + "\n")
	if p.LocalIP != "" {
		b.WriteString("localIP = " + tomlStr(p.LocalIP) + "\n")
	}
	if p.LocalPort > 0 {
		b.WriteString("localPort = " + strconv.Itoa(p.LocalPort) + "\n")
	}
	switch typ {
	case "tcp", "udp":
		b.WriteString("remotePort = " + strconv.Itoa(p.RemotePort) + "\n")
	case "http", "https":
		if p.CustomDomains != "" {
			b.WriteString("customDomains = [" + tomlStrList(p.CustomDomains) + "]\n")
		}
		if p.Subdomain != "" {
			b.WriteString("subdomain = " + tomlStr(p.Subdomain) + "\n")
		}
	case "stcp", "sudp", "xtcp":
		b.WriteString("secretKey = " + tomlStr(p.SecretKey) + "\n")
	}
	if p.UseEncryption {
		b.WriteString("transport.useEncryption = true\n")
	}
	if p.UseCompression {
		b.WriteString("transport.useCompression = true\n")
	}
	return b.String()
}

// tomlStrList 把逗号分隔的字符串转成 toml 字符串数组。
func tomlStrList(s string) string {
	parts := strings.Split(s, ",")
	quoted := make([]string, 0, len(parts))
	for _, p := range parts {
		if v := strings.TrimSpace(p); v != "" {
			quoted = append(quoted, tomlStr(v))
		}
	}
	return strings.Join(quoted, ", ")
}

func defaultStr(v, def string) string {
	if v == "" {
		return def
	}
	return v
}
